# Generated by Django 4.0.1 on 2022-02-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='followed_id',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
