# Generated by Django 4.0.1 on 2022-03-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=20, unique=True)),
                ('connections', models.IntegerField()),
            ],
        ),
    ]
