# Generated by Django 4.0.1 on 2022-01-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
