# Generated by Django 4.0.1 on 2022-02-05 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments_listing_comments_user_listings_winner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bids',
        ),
        migrations.AddField(
            model_name='listings',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
