# Generated by Django 4.0.1 on 2022-02-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listings_description_alter_listings_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
