# Generated by Django 4.0.1 on 2022-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listings_current_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
